name: imagej
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.7
  - conda-forge::python
  - conda-forge::pyimagej
  - conda-forge::openjdk=8.0.152=h46b5887_1
  - numpy
  - scipy
  - pandas
  - pip:
    - scikit-image
    - scikit-learn
    - pandas
    - pillow
    - imjoy-rpc>=0.2.5
    - imjoy-jupyter-extension
    - imjoy-elfinder
